selection: {'fKFChi2PrimProton': 'fKFChi2PrimProton > -10 and fKFChi2PrimProton < 1000',
            'fKFChi2PrimKaon': 'fKFChi2PrimKaon > -10 and fKFChi2PrimKaon < 1000',
            'fKFChi2PrimPion': 'fKFChi2PrimPion > -10 and fKFChi2PrimPion < 1000',
            'fKFDcaPionKaon': 'fKFDcaPionKaon < 1',
            'fKFDcaProtonKaon': 'fKFDcaProtonKaon < 1',
            'fKFDcaProtonPion': 'fKFDcaProtonKaon < 1',
            'fLiteImpactParameter0': 'fLiteImpactParameter0 > -1 and fLiteImpactParameter0 < 1',
            'fLiteImpactParameter1': 'fLiteImpactParameter1 > -1 and fLiteImpactParameter1 < 1',
            'fLiteImpactParameter2': 'fLiteImpactParameter2 > -1 and fLiteImpactParameter2 < 1',
            'fLiteCpa': 'fLiteCpa > -1 and fLiteCpa < 1',
            'fLiteCpaXY': 'fLiteCpaXY > -1 and fLiteCpaXY < 1',
            'fKFChi2Geo': 'fKFChi2Geo > -10 and fKFChi2Geo < 100',
            'fKFChi2GeoPionKaon': 'fKFChi2GeoPionKaon > -10 and fKFChi2GeoPionKaon < 100',
            'fKFChi2GeoProtonKaon': 'fKFChi2GeoProtonKaon > -10 and fKFChi2GeoProtonKaon < 100',
            'fKFChi2GeoProtonPion': 'fKFChi2GeoProtonPion > -10 and fKFChi2GeoProtonPion < 100',
            'fKFChi2Topo': 'fKFChi2Topo > -10 and fKFChi2Topo < 100',
            'fKFDecayLengthNormalised': 'fKFDecayLengthNormalised > -10 and fKFDecayLengthNormalised < 100',
            'fKFNSigTpcTofPr': 'fKFNSigTpcTofPr < 5',
            'fKFNSigTpcTofKa': 'fKFNSigTpcTofKa < 5',
            'fKFNSigTpcTofPi': 'fKFNSigTpcTofPi < 5',
            'fLiteY': 'fLiteY > -0.8 and fLiteY < 0.8',
            'fLiteM': 'fLiteM > 2.12 and fLiteM < 2.42'
            }
