input_file_pattern: "/lustre/alice/users/lubynets/WORKDIR/tree2pandas/PlainTree.data"
input_file_from: 1
input_file_to: 1
input_tree: "pTree"
output_path: "/lustre/alice/users/lubynets/WORKDIR/tree2pandas"
output_file_key: "fileOut"
