selection: {'fKFChi2PrimKaon': 'fKFChi2PrimKaon > -10 and fKFChi2PrimKaon < 1000',
            'fLiteImpactParameter0': 'fLiteImpactParameter0 > -1 and fLiteImpactParameter0 < 1',
            'fLiteImpactParameter1': 'fLiteImpactParameter1 > -1 and fLiteImpactParameter1 < 1',
            'fLiteImpactParameter2': 'fLiteImpactParameter2 > -1 and fLiteImpactParameter2 < 1',
            'fLiteCpa': 'fLiteCpa > -1 and fLiteCpa < 1',
            'fLiteCpaXY': 'fLiteCpaXY > -1 and fLiteCpaXY < 1',
            'fKFChi2Geo': 'fKFChi2Geo > -10 and fKFChi2Geo < 100',
            'fKFChi2Topo': 'fKFChi2Topo > -10 and fKFChi2Topo < 100',
            'fKFDecayLengthNormalised': 'fKFDecayLengthNormalised > -10 and fKFDecayLengthNormalised < 100',
            'fKFMassInv': 'fKFMassInv > 2.12 and fKFMassInv < 2.42'
            }
