selection: {'fKFChi2PrimProton': 'fKFChi2PrimProton > -100 and fKFChi2PrimProton < 1000',
            'fKFChi2PrimKaon': 'fKFChi2PrimKaon > -100 and fKFChi2PrimKaon < 1000',
            'fKFChi2PrimPion': 'fKFChi2PrimPion > -100 and fKFChi2PrimPion < 1000',
            'fKFChi2Geo': 'fKFChi2Geo > -100 and fKFChi2Geo < 1000',
            'fKFChi2Topo': 'fKFChi2Topo > -100 and fKFChi2Topo < 1000',
            'fLiteNSigTpcPr': 'fLiteNSigTpcPr > -100 and fLiteNSigTpcPr < 100',
            'fLiteNSigTpcKa': 'fLiteNSigTpcKa > -100 and fLiteNSigTpcKa < 100',
            'fLiteNSigTpcPi': 'fLiteNSigTpcPi > -100 and fLiteNSigTpcPi < 100',
            'fKFDecayLengthNormalised': 'fKFDecayLengthNormalised > -100 and fKFDecayLengthNormalised < 1000',
            'fKFMassInv': 'fKFMassInv > 2.12 and fKFMassInv < 2.42'
            }
