hyperpar_study_file: ""
hyperpar_study_ntrials: 15
hyperpar_study_timeout: 7200
save_hyperpar_study: True
model_version: "v1"
slice_var_name: "pT"
slice_var_treename: "fKFPt"
slice_var_unit: "GeV/c"
sidebands: [2.12, 2.20, 2.38, 2.42]
training_variables: [
                     'fLiteImpactParameter0',
                     'fLiteImpactParameter1',
                     'fLiteImpactParameter2',
                     'fLiteCpa',
                     'fLiteCpaXY'
                     ]
keep_variables: ['fKFPt', 'fKFMassInv', 'fKFT', 'fLiteY', 'fKFSigBgStatus']
draw_vars_dict:
  Basic:
    - fKFPt
    - fKFMassInv
    - fKFT
    - fLiteY
  Others:
    - fLiteCpa
    - fLiteCpaXY
  ImpactParameter:
    - fLiteImpactParameter0
    - fLiteImpactParameter1
    - fLiteImpactParameter2
